### PR TITLE
Fix getJSON() accidentally writing cookie with too many arguments

### LINKED ISSUE #417: getJSON called with many arguments doesn't behave as expected
Following up on #416 

@carhartl
> getJSON(), in contrast to get(), we‘re passing on all given arguments. So what‘s actually happening when you called it with two arguments is each time a cookie is written (due to the api’s underlying implementation). You won’t notice the difference if the values remain the same, but that seems to be a bug. cc @FagnerMartinsBrack 

@carhartl 
> We have:

```
api.getJSON = function () {
    return api.apply({
        json: true
	}, arguments);
};
```
> and I believe we should have:

```
api.getJSON = function (key) {
    return api.call({ json: true }, key);
};
```

@carhartl 

> I believe it’s worse..

```
cookies.getJSON(k, {domain: 'a'})
```
> would result in a cookie k written with a value of json stringified {domain: 'a'}. Cannot test this right now.

### PR DESCRIPTION
**Pull request by carhartl**
Addresses #417 (for context see there).

- [x] Fix implementation
- [x] Brushup documentation

~Note: I needed to change a test (see e22693488a6c31e9f54d5f4734b92968ace8ea2e), unrelated to the PR, because it was failing due to upcoming DST change, and the expires date was lying after that change, resulting in a date string mismatch. I reduced the likelihood of this happening again by reducing the amount of days expires will be ahead of "now", but there should be a way how to make this proof once and for all.~[-> commit went out of PR to master]

### CODE REVIEW

File: test/tests.js [hunk 1]
```diff
@@ -180,10 +180,10 @@ QUnit.test('undefined', function (assert) {
 
 QUnit.test('expires option as days from now', function (assert) {
 	assert.expect(1);
-	var sevenDaysFromNow = new Date();
-	sevenDaysFromNow.setDate(sevenDaysFromNow.getDate() + 21);
-	var expected = 'expires=' + sevenDaysFromNow.toUTCString();
-	var actual = Cookies.set('c', 'v', { expires: 21 });
+	var expires = new Date();
```
Comment (carhartl) [inline test/tests.js]: "Seven days from now" had become twenty-one days from now in the meantime, so I changed the naming.

**Comment by carhartl** [comment]
@FagnerMartinsBrack Let me know whether we should first fix the expires related test in a separate commit/PR (-> e22693488a6c31e9f54d5f4734b92968ace8ea2e), and remove it from this PR.

**Comment by carhartl** [comment]
Brushing up documentation as part of this PR?

**Comment by FagnerMartinsBrack** [comment]
> @FagnerMartinsBrack Let me know whether we should first fix the expires related test in a separate commit/PR (-> e226934), and remove it from this PR.

I think you can commit on `master` the fix that this PR is dependent upon. I'm having the same test failure 😆

File: src/js.cookie.js [hunk 2]
```diff
@@ -140,10 +140,10 @@
 		api.get = function (key) {
 			return api.call(api, key);
 		};
-		api.getJSON = function () {
-			return api.apply({
+		api.getJSON = function (key) {
+			return api.call({
```
Comment (FagnerMartinsBrack) [inline src/js.cookie.js]: Any byte size impact or none?

**Comment by FagnerMartinsBrack** [comment]
<sup>I wonder how many contributors are not contributing due to this test failure 😞😞😞 </sup>

**Comment by carhartl** [comment]
> I wonder how many contributors are not contributing due to this test failure in the local dev environment

😢 I'm going to look for a proper solution next.

File: src/js.cookie.js (hunk 2 above)
Comment (carhartl) [reply src/js.cookie.js]: I haven't had coffee, but I think it's an improvement even:

bildschirmfoto 2018-03-21 um 07 41 04

**Comment by carhartl** [comment]
Regarding the expires test -> #419

**Comment by carhartl** [comment]
So there were 42 days in a year where this test was failing... 😭 

(At least we've reduced it to 2 now.)

File: src/js.cookie.js (hunk 2 above)
Comment (FagnerMartinsBrack) [reply src/js.cookie.js]: o.O wow

**Comment by FagnerMartinsBrack** [comment]
We should probably close off v2.2.1 with [these issues](https://github.com/js-cookie/js-cookie/milestone/10).

File: test/tests.js [hunk 3]
```diff
@@ -474,6 +474,11 @@ QUnit.test('Cookies with escaped quotes in json using raw converters', function
 	assert.strictEqual(Cookies.get('c'), '{ \\"foo\\": \\"bar\\" }', 'returns unparsed cookie with enclosing quotes removed');
 });
 
+QUnit.test('Prevent accidentally writing cookie when passing unexpected argument', function (assert) {
+	Cookies.getJSON('c', { foo: 'bar' });
+	assert.strictEqual(document.cookie, '', 'should not write any cookie');
```
[the remark this answers is not in the document]
Comment (carhartl) [reply test/tests.js]: I've fixed this...

**Comment by carhartl** [comment]
@FagnerMartinsBrack Added the documenation part... do you think it's sufficient?

File: README.md [hunk 4]
```diff
@@ -95,6 +95,18 @@ Read all visible cookies:
...
+have been used when writing the cookie in question):*
+
+```javascript
+Cookies.get('foo', domain: 'sub.example.com'); // `domain` won't have any effect...!
+```
+
+That is, if a cookie with the name `foo` is visible from where `get()` was called,
+it's the one that is being read, no matter the domain or path. This also means that no guarantee
+can be made regarding which cookie is being retrieved in case one cookie is shadowing another,
+similarly named one with a differently scoped `domain` and/or `path` attribute.
```
Comment (FagnerMartinsBrack) [inline README.md]: I'm not sure of the shadowing case should be documented here? Is it related to the issue we're trying to solve here? Have you tested it?

We have [an issue](https://github.com/js-cookie/js-cookie/issues/226) to document the shadowing cookie problem.

File: README.md [hunk 5]
```diff
@@ -95,6 +95,18 @@ Read all visible cookies:
...
 ```
 
+*Note: It is not possible to read a particular cookie by passing one of the cookie attributes (which may or may not
+have been used when writing the cookie in question):*
+
+```javascript
+Cookies.get('foo', domain: 'sub.example.com'); // `domain` won't have any effect...!
+```
+
+That is, if a cookie with the name `foo` is visible from where `get()` was called,
```
Comment (FagnerMartinsBrack) [inline README.md]: Could we restructure like:

```
The cookie with the name `foo` will only be available on `.get()` if it's visible from where the code is called.
```

File: README.md [hunk 6]
```diff
@@ -95,6 +95,18 @@ Read all visible cookies:
 Cookies.get(); // => { name: 'value' }
 ```
 
+*Note: It is not possible to read a particular cookie by passing one of the cookie attributes (which may or may not
+have been used when writing the cookie in question):*
+
+```javascript
+Cookies.get('foo', domain: 'sub.example.com'); // `domain` won't have any effect...!
```
Comment (FagnerMartinsBrack) [inline README.md]: Missing braces: `Cookies.get('foo', { domain: 'sub.example.com' });`

File: README.md [hunk 7]
```diff
@@ -95,6 +95,18 @@ Read all visible cookies:
 Cookies.get(); // => { name: 'value' }
 ```
 
+*Note: It is not possible to read a particular cookie by passing one of the cookie attributes (which may or may not
```
Comment (FagnerMartinsBrack) [inline README.md]: "It is not possible to `.get()` a particular cookie..."?

**Comment by FagnerMartinsBrack** [comment]
@carhartl I've made some comments

File: README.md (hunk 7 above)
Comment (carhartl) [reply README.md]: In plain text I don't see what's wrong with using "read"... that's how the operation is usually referred to imo.

Comment (FagnerMartinsBrack) [reply README.md]: That's fine, just wondering if it would make more sense. LGTM
